[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rag-admission-assistant"
version = "0.1.0"
description = "RAG chatbot for university admission"
requires-python = ">=3.11"

dependencies = [
    # --- configs ---
    "pyyaml",
    # --- chunking ---
    "langchain-text-splitters",
    "nltk",
    # --- embeddings ---
    "numpy",
    "torch",
    "sentence-transformers>=2.7.0",
    "transformers>=4.51.0",
    "huggingface-hub",

    # --- retrieval ---
    "qdrant-client",

]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["src"]