common:
  length_unit: characters
  sentence_language: russian

  ks:
    - 1
    - 3
    - 5


method_experiment:
  strategies:
    - recursive
    - sentence
    - markdown
    - markdown_recursive

  chunk_size: 600
  chunk_overlap: 64

size_experiments:
  strategy: markdown_recursive
  overlap: 64

  chunk_sizes:
   - 600
   - 800
   - 1000
   - 1200


overlap_experiment:
  strategy: markdown_recursive
  chunk_size: 1000

  chunk_overlaps:
    - 0
    - 32
    - 64
    - 128
    - 256