common:
  length_unit: characters
  sentence_language: russian

  ks:
    - 1
    - 3
    - 5


method_experiment:
  strategies:
    - recursive
    - markdown_recursive

  chunk_size: 1000
  chunk_overlap: 64