common:
  ks:
    - 1
    - 3
    - 5

  batch_size: 32

  warmup_documents: 32
  warmup_queries: 5
  query_repeats: 1


models:
  e5_small:
    model_id: intfloat/multilingual-e5-small
    query_prefix: "query: "
    document_prefix: "passage: "

  e5_base:
    model_id: intfloat/multilingual-e5-base
    query_prefix: "query: "
    document_prefix: "passage: "

  bge_m3:
    model_id: BAAI/bge-m3
    query_prefix: ""
    document_prefix: ""

  qwen3_06b:
    model_id: Qwen/Qwen3-Embedding-0.6B

    query_instruction: >-
      Given a user question about university admission,
      retrieve relevant passages that contain the information
      needed to answer the question.

    query_prefix: ""
    document_prefix: ""